//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TiagoTelepresenceControllers
{
    [Serializable]
    public class ArmMotionRequest : Message
    {
        public const string k_RosMessageName = "tiago_telepresence_controllers/ArmMotion";
        public override string RosMessageName => k_RosMessageName;

        public string command;

        public ArmMotionRequest()
        {
            this.command = "";
        }

        public ArmMotionRequest(string command)
        {
            this.command = command;
        }

        public static ArmMotionRequest Deserialize(MessageDeserializer deserializer) => new ArmMotionRequest(deserializer);

        private ArmMotionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "ArmMotionRequest: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
